defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/repo

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save node modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn ci:test
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish to NPM
          command: yarn ci:publish

workflows:
  version: 2
  test_and_release:
    jobs:
      - setup
      - tests:
          requires:
            - setup
      - publish:
          requires:
            - tests
          filters:
            branches:
              only:
                - master
